## <span style='color:#ffb5c0'>**Exploratory Data Analysis, February 20th, 2026**

In [1]:
import pandas as pd
import numpy as np

In [2]:
import holoviews as hv
import hvplot.pandas
from holoviews import opts

In [3]:
data = pd.read_csv("ELA_data_2013_2023.csv")

### <span style='color:#ffb5c0'>**Data Feasibility Review & Data Cleaning/Preprocessing**

The initial data contains 626,462 rows and 18 columns. After filtering for years 2018, 2019, and 2022, the data contains 220,443 rows. Almost all columns do not have missing values, with the exception for school name. This is due to the data containing citywide and district level metrics, so school name is not applicable. 

The data was filtered to contain only years surrounding the COVID-19 pandemic, as this is the time period of interest. Unfortunately, data was not given for the years 2020 and 2021, due to cancelled and optional testing, respectively. All scores and levels (number and percentages) were converted to floats. The year was converted to an object. Groups with five or less tested students were suppressed with a value "s". Within this data, 58,872 rows are missing observations for scores and level breakdowns. These observations have been omitted.

In [4]:
from data_cleaning import cleaning_data, change_variable_type
school_data = cleaning_data(data) # filter for year, rename some vars

# convert num columns
cols = ['mean_scale_score','level_1_count','level_2_count','level_3_count', 'level_4_count', 'level_4_percentage', 'level_3_4_count',
        'level_1_percentage','level_2_percentage','level_3_percentage','level_4_percentage','level_3_4_percentage']
school_data = change_variable_type(school_data,cols)
# change year to ob
school_data['Year'] = school_data['Year'].astype('object')

In [5]:
# school_data.info()

In [6]:
# school_data_filtered = school_data[
#     ~(school_data['Report Category'].isin(['Citywide','School','Borough']))]

school_data_filtered = school_data[
    (school_data['Report Category'].isin(['District'])) &
    (school_data['Grade'] == 'All Grades') &
    (school_data['Student Category'] == 'All Students')
    ]

### <span style='color:#ffb5c0'>**Ethics and Bias Considerations** </span>

This data is very heavily balanced regarding different socioeconomic categories. There are some disparities with gender by ethnicity, however these indicators will not be used. The same can be said for grade, where there is sufficient distribution.

### <span style='color:#ffb5c0'> **Poverty Data, by School District**

Citizen's Committee for Children of New York <br>
https://data.cccnewyork.org/data/map/1370/student-economic-status#1370/a/5/1610/127/a/a

In [7]:
# eco = pd.read_csv('student_economic_status.csv')

In [8]:
# eco['TimeFrame'] = eco['TimeFrame'].astype('Int64')
# eco['TimeFrame'] = eco['TimeFrame'].astype('object')

In [9]:
# eco_filter = eco[
#     (eco['TimeFrame'] == 2019) &
#     (eco['DataFormat'] == 'Percent') &
#     ~(eco['Fips'].isin(['3651000', '36061', '36005', '36047', '36081', '36085']))]

In [10]:
# eco_filter['Fips'] = eco_filter['Fips'].replace({'SD1':'1', 'SD2':'2', 'SD3':'3', 'SD4':'4', 'SD5':'5', 'SD6':'6', 'SD7':'7', 'SD8':'8', 'SD9':'9',
#                                          'SD10':'10', 'SD11':'11', 'SD12':'12', 'SD13':'13', 'SD14':'14', 'SD15':'15', 'SD16':'16', 'SD17':'17', 'SD18':'18',
#                                          'SD19':'19', 'SD20':'20', 'SD21':'21', 'SD22':'22', 'SD23':'23', 'SD24':'24', 'SD25':'25', 'SD26':'26', 'SD27':'27', 'SD28':'28', 'SD29':'29',
#                                          'SD30':'30', 'SD31':'31', 'SD32':'32'})

In [11]:
# eco_filter= eco_filter.rename(columns = {'Fips':'District'})
# school_data_filtered= school_data_filtered.rename(columns = {'Geographic Subdivision':'District'})

In [12]:
# merged_data = school_data_filtered.merge(eco_filter, on='District', how='left')

In [13]:
# nyc_poverty_percent = 0.7276

In [14]:
# def categorize_poverty(row):
#     if row['Data'] >= nyc_poverty_percent:
#         return '1'
#     else:
#         return '0'

In [15]:
# merged_data['Poverty_Category'] = merged_data.apply(categorize_poverty, axis=1)

In [16]:
# p_data= (merged_data.groupby(['Year','Poverty_Category'])[
#     ['level_1_percentage',
#      'level_2_percentage',
#      'level_3_percentage',
#      'level_4_percentage',
#      'level_3_4_percentage',
#      'mean_scale_score'
#      ]
# ].mean())

# p1= p_data.hvplot.line(
#     x = 'Year',
#     y = 'mean_scale_score',
#     by = 'Poverty_Category'
# ).opts(ylabel = 'Level 1 %')

# p1

In [17]:
# p_data= (merged_data.groupby(['Year','Poverty_Category'])[
#     ['level_1_percentage',
#      'level_2_percentage',
#      'level_3_percentage',
#      'level_4_percentage',
#      'level_3_4_percentage',
#      'mean_scale_score'
#      ]
# ].mean())

# p1= p_data.hvplot.line(
#     x = 'Year',
#     y = 'level_1_percentage',
#     by = 'Poverty_Category'
# ).opts(ylabel = 'Level 1 %')


# p2 = p_data.hvplot.line(
#     x = 'Year',
#     y = 'level_2_percentage',
#     by = 'Poverty_Category'
# ).opts(ylabel = 'Level 2 %')

# p3 = p_data.hvplot.line(
#     x = 'Year',
#     y = 'level_3_percentage',
#     by = 'Poverty_Category'
# ).opts(ylabel = 'Level 3 %')

# p4 = p_data.hvplot.line(
#     x = 'Year',
#     y = 'level_4_percentage',
#     by = 'Poverty_Category'
# ).opts(ylabel = 'Level 4 %')

# p5 = p_data.hvplot.line(
#     x = 'Year',
#     y = 'level_3_4_percentage',
#     by = 'Poverty_Category'
# ).opts(ylabel = 'Level 3 & 4 %')

# p6 = p_data.hvplot.line(
#     x = 'Year',
#     y = 'mean_scale_score',
#     by = 'Poverty_Category'
# ).opts(ylabel = 'Mean Scale Score')


# layout1 = (p1 + p2 + p3 + p4 + p5 + p6).cols(2)
# layout1

In [18]:
# print(school_data['school_name'].nunique())

### <span style='color:#ffb5c0'> **Poverty Data, for District Level Information**

New York City OpenData Demographic Snapshot <br>
https://data.cityofnewyork.us/Education/2017-18-2021-22-Demographic-Snapshot/c7ru-d68s/about_data

In [19]:
district_poverty = pd.read_excel('Demographic_Snapshot_2017-18_to_2021-22__Public_.xlsx', sheet_name = 'District')

In [20]:
district_poverty

,Administrative District,Year,Total Enrollment,Grade 3K,Grade PK (Half Day & Full Day),Grade K,Grade 1,Grade 2,Grade 3,Grade 4,...,% White,# Missing Race/Ethnicity Data,% Missing Race/Ethnicity Data,# Students with Disabilities,% Students with Disabilities,# English Language Learners,% English Language Learners,# Poverty,% Poverty,Economic Need Index
0,1,2017-18,11632,0,800,851,846,854,862,839,...,0.173831,29,0.002493,2528,0.217331,1016,0.087345,7682,0.660420,0.670163
1,1,2018-19,11376,0,759,799,850,816,838,839,...,0.179764,38,0.003340,2597,0.228288,966,0.084916,7314,0.642932,0.661232
2,1,2019-20,11506,211,749,812,782,848,813,818,...,0.178689,126,0.010951,2593,0.225361,919,0.079871,7419,0.644794,0.676958
3,1,2020-21,11021,209,623,728,762,746,787,775,...,0.180746,101,0.009164,2501,0.226930,919,0.083386,7087,0.643045,0.670118
4,1,2021-22,10327,347,524,685,701,686,680,707,...,0.180014,29,0.002808,2355,0.228043,814,0.078823,6463,0.625835,0.653216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,84,2017-18,113528,0,533,11445,12016,11447,10857,10032,...,0.043848,280,0.002466,20002,0.176186,7859,0.069225,92292,0.812945,0.755627
171,84,2018-19,119551,0,524,12001,12103,11765,10955,10196,...,0.043488,281,0.002350,21281,0.178008,8264,0.069125,96585,0.807898,0.753894
172,84,2019-20,129668,0,572,13217,13130,12313,11798,10928,...,0.042539,269,0.002075,23257,0.179358,9256,0.071382,104010,0.802125,0.781033
173,84,2020-21,138648,0,636,13122,13775,13331,12526,11982,...,0.043650,445,0.003210,25299,0.182469,10755,0.077571,112037,0.808068,0.780144
174,84,2021-22,139752,0,863,12299,13122,13154,12688,11963,...,0.043692,495,0.003542,25075,0.179425,12655,0.090553,111488,0.797756,0.774605

In [21]:
cols_to_keep = ['Administrative District','Year','% Poverty']
district_poverty_filtered = district_poverty[
    (district_poverty['Year'] == '2018-19') & 
    ~(district_poverty['Administrative District'].isin([75,79,84]))][cols_to_keep]

In [22]:
district_poverty_filtered['Administrative District'] = district_poverty_filtered['Administrative District'].astype('object')

In [23]:
district_poverty_filtered['% Poverty'] = district_poverty_filtered['% Poverty'].replace({'Above 95%':'0.95'})

In [24]:
district_level_data = school_data[
    (school_data['Report Category'].isin(['District'])) &
    (school_data['Grade'] == 'All Grades') &
    (school_data['Student Category'] == 'All Students')
    ]

In [48]:
district_level_data= district_level_data.rename(columns = {'Geographic Subdivision':'Administrative District'})

In [49]:
district_poverty_filtered

    Administrative District     Year  % Poverty
1                         1  2018-19   0.642932
6                         2  2018-19   0.531863
11                        3  2018-19   0.489436
16                        4  2018-19   0.813852
21                        5  2018-19   0.818708
26                        6  2018-19   0.853175
31                        7  2018-19   0.916370
36                        8  2018-19   0.832162
41                        9  2018-19   0.924517
46                       10  2018-19   0.831589
51                       11  2018-19   0.783517
56                       12  2018-19   0.921567
61                       13  2018-19   0.647896
66                       14  2018-19   0.726526
71                       15  2018-19   0.565744
76                       16  2018-19   0.838399
81                       17  2018-19   0.800582
86                       18  2018-19   0.774557
91                       19  2018-19   0.883512
96                       20  2018-19   0.771452
101                      21  2018-19   0.728727
106                      22  2018-19   0.703402
111                      23  2018-19   0.898278
116                      24  2018-19   0.761976
121                      25  2018-19   0.690140
126                      26  2018-19   0.574056
131                      27  2018-19   0.753754
136                      28  2018-19   0.694165
141                      29  2018-19   0.732208
146                      30  2018-19   0.704468
151                      31  2018-19   0.578126
156                      32  2018-19   0.890199

In [58]:
district_level_data['Administrative District'] = district_level_data['Administrative District'].astype(str)
district_poverty_filtered['Administrative District'] = district_poverty_filtered['Administrative District'].astype(str)

In [59]:
merged_dis= district_level_data.merge(
    district_poverty_filtered[['Administrative District', '% Poverty']],  # keep only needed columns
    on='Administrative District',
    how='left'
)

In [60]:
merged_dis

,Report Category,Administrative District,school_name,Grade,Year,Student Category,number_tested,mean_scale_score,level_1_count,level_1_percentage,level_2_count,level_2_percentage,level_3_count,level_3_percentage,level_4_count,level_4_percentage,level_3_4_count,level_3_4_percentage,% Poverty
0,District,1,NaN,All Grades,2022,All Students,3283,605.0,650.0,19.8,871.0,26.5,793.0,24.2,969.0,29.5,1762.0,53.7,0.642932
1,District,1,NaN,All Grades,2019,All Students,4103,605.0,794.0,19.4,1055.0,25.7,1079.0,26.3,1175.0,28.6,2254.0,54.9,0.642932
2,District,2,NaN,All Grades,2022,All Students,12669,614.0,1024.0,8.1,2228.0,17.6,3932.0,31.0,5485.0,43.3,9417.0,74.3,0.531863
3,District,2,NaN,All Grades,2019,All Students,15264,613.0,1325.0,8.7,2528.0,16.6,5076.0,33.3,6335.0,41.5,11411.0,74.8,0.531863
4,District,3,NaN,All Grades,2022,All Students,6319,609.0,919.0,14.5,1324.0,21.0,1760.0,27.9,2316.0,36.7,4076.0,64.5,0.489436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,District,30,NaN,All Grades,2019,All Students,17880,604.0,3288.0,18.4,4809.0,26.9,5322.0,29.8,4461.0,24.9,9783.0,54.7,0.704468
60,District,31,NaN,All Grades,2022,All Students,23476,604.0,4336.0,18.5,6265.0,26.7,6975.0,29.7,5900.0,25.1,12875.0,54.8,0.578126
61,District,31,NaN,All Grades,2019,All Students,26058,603.0,5243.0,20.1,7077.0,27.2,7901.0,30.3,5837.0,22.4,13738.0,52.7,0.578126
62,District,32,NaN,All Grades,2022,All Students,4023,595.0,1340.0,33.3,1228.0,30.5,906.0,22.5,549.0,13.6,1455.0,36.2,0.890199
63,District,32,NaN,All Grades,2019,All Students,5258,594.0,1715.0,32.6,1681.0,32.0,1228.0,23.4,634.0,12.1,1862.0,35.4,0.890199

In [61]:
def categorize_poverty(row):
    if row['% Poverty'] >= nyc_poverty_percent:
        return '1'
    else:
        return '0'
    
nyc_poverty_percent = 0.74

In [64]:
merged_dis['% Poverty'] = merged_dis['% Poverty'].astype(float)
merged_dis['Poverty_Category'] = merged_dis.apply(categorize_poverty, axis=1) 
merged_dis['% Poverty'] = merged_dis['% Poverty'].round(3)

In [65]:
p_data_dis= (merged_dis.groupby(['Year','Poverty_Category'])[
    ['level_1_percentage',
     'level_2_percentage',
     'level_3_percentage',
     'level_4_percentage',
     'level_3_4_percentage',
     'mean_scale_score'
     ]
].mean())

p1= p_data_dis.hvplot.line(
    x = 'Year',
    y = 'level_1_percentage',
    by = 'Poverty_Category'
).opts(ylabel = 'Level 1 %')


p2 = p_data_dis.hvplot.line(
    x = 'Year',
    y = 'level_2_percentage',
    by = 'Poverty_Category'
).opts(ylabel = 'Level 2 %')

p3 = p_data_dis.hvplot.line(
    x = 'Year',
    y = 'level_3_percentage',
    by = 'Poverty_Category'
).opts(ylabel = 'Level 3 %')

p4 = p_data_dis.hvplot.line(
    x = 'Year',
    y = 'level_4_percentage',
    by = 'Poverty_Category'
).opts(ylabel = 'Level 4 %')

p5 = p_data_dis.hvplot.line(
    x = 'Year',
    y = 'level_3_4_percentage',
    by = 'Poverty_Category'
).opts(ylabel = 'Level 3 & 4 %')

p6 = p_data_dis.hvplot.line(
    x = 'Year',
    y = 'mean_scale_score',
    by = 'Poverty_Category'
).opts(ylabel = 'Mean Scale Score')


layout1 = (p1 + p2 + p3 + p4 + p5 + p6).cols(2)
layout1

:Layout
   .NdOverlay.I   :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (level_1_percentage)
   .NdOverlay.II  :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (level_2_percentage)
   .NdOverlay.III :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (level_3_percentage)
   .NdOverlay.IV  :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (level_4_percentage)
   .NdOverlay.V   :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (level_3_4_percentage)
   .NdOverlay.VI  :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (mean_scale_score)

### <span style='color:#ffb5c0'> **Poverty Data, for School Level Information**

New York City OpenData Demographic Snapshot <br>
https://data.cityofnewyork.us/Education/2017-18-2021-22-Demographic-Snapshot/c7ru-d68s/about_data

In [32]:
school_poverty = pd.read_excel('Demographic_Snapshot_2017-18_to_2021-22__Public_.xlsx', sheet_name = 'School')

In [33]:
cols_to_keep = ['DBN','School Name','Year','% Poverty']
school_poverty_filtered = school_poverty[
    (school_poverty['Year'] == '2018-19')][cols_to_keep]

In [34]:
# all schools w poverty levels > 0.95 were labelled as "Above 95%", puts 0.95 inplace
school_poverty_filtered['% Poverty'] = school_poverty_filtered['% Poverty'].replace({'Above 95%':'0.95'})

**Citywide Poverty % for 2018-19 school year was 74%**

In [35]:
school_level_data = school_data[
    (school_data['Report Category'].isin(['School'])) &
    (school_data['Grade'] == 'All Grades') &
    (school_data['Student Category'] == 'All Students')
    ]

In [36]:
school_poverty_filtered['School Name'].nunique()

1821

In [37]:
school_level_data['school_name'].nunique()

1119

In [38]:
school_level_data= school_level_data.rename(columns = {'Geographic Subdivision':'DBN'})

In [39]:
merged = school_level_data.merge(
    school_poverty_filtered[['DBN', '% Poverty']],  # keep only needed columns
    on='DBN',
    how='left'
)

In [40]:
def categorize_poverty(row):
    if row['% Poverty'] >= nyc_poverty_percent:
        return '1'
    else:
        return '0'
    
nyc_poverty_percent = 0.74

In [41]:
merged['% Poverty'] = merged['% Poverty'].astype(float)

In [42]:
merged['Poverty_Category'] = merged.apply(categorize_poverty, axis=1) 
merged['% Poverty'] = merged['% Poverty'].round(3)

In [43]:
p_data= (merged.groupby(['Year','Poverty_Category'])[
    ['level_1_percentage',
     'level_2_percentage',
     'level_3_percentage',
     'level_4_percentage',
     'level_3_4_percentage',
     'mean_scale_score'
     ]
].mean())

p1= p_data.hvplot.line(
    x = 'Year',
    y = 'level_1_percentage',
    by = 'Poverty_Category'
).opts(ylabel = 'Level 1 %')


p2 = p_data.hvplot.line(
    x = 'Year',
    y = 'level_2_percentage',
    by = 'Poverty_Category'
).opts(ylabel = 'Level 2 %')

p3 = p_data.hvplot.line(
    x = 'Year',
    y = 'level_3_percentage',
    by = 'Poverty_Category'
).opts(ylabel = 'Level 3 %')

p4 = p_data.hvplot.line(
    x = 'Year',
    y = 'level_4_percentage',
    by = 'Poverty_Category'
).opts(ylabel = 'Level 4 %')

p5 = p_data.hvplot.line(
    x = 'Year',
    y = 'level_3_4_percentage',
    by = 'Poverty_Category'
).opts(ylabel = 'Level 3 & 4 %')

p6 = p_data.hvplot.line(
    x = 'Year',
    y = 'mean_scale_score',
    by = 'Poverty_Category'
).opts(ylabel = 'Mean Scale Score')


layout1 = (p1 + p2 + p3 + p4 + p5 + p6).cols(2)
layout1

:Layout
   .NdOverlay.I   :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (level_1_percentage)
   .NdOverlay.II  :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (level_2_percentage)
   .NdOverlay.III :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (level_3_percentage)
   .NdOverlay.IV  :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (level_4_percentage)
   .NdOverlay.V   :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (level_3_4_percentage)
   .NdOverlay.VI  :NdOverlay   [Poverty_Category]
      :Curve   [Year]   (mean_scale_score)

In [44]:
merged.hvplot.hist(
    y = '% Poverty',
    by = 'Year',
    bins = 30,
    title = 'Poverty % Distribution - 2019 and 2022'
)

:NdOverlay   [Year]
   :Histogram   [% Poverty]   (Count)

Poverty percentage is left-skewed. This does not entirely effect TWFE DID analysis, normality is not an assumption.

In [45]:
merged.hvplot.scatter(
    x  = '% Poverty',
    y = 'mean_scale_score',
    by = 'Year'
).opts(xlabel='Poverty %', ylabel='Mean Score', width = 900, height = 600)

:NdOverlay   [Year]
   :Scatter   [% Poverty]   (mean_scale_score)