In [1]:
def cleaning_data(df):
    ''' This function cleans the data, filters by years I want to use, changes column names,
    Returns cleaned dataset.'''
    # clean_df = df.dropna(axis ='rows')
    clean_df = df[df['Year'].isin([2018,2019,2022,2023])]

    # rename columns for easier use in code
    clean_df = clean_df.rename({'DBN': 'dbn',
                                'School Name': 'school_name',
                                'Number Tested': "number_tested",
                                'Mean Scale Score':"mean_scale_score",
                                'Num Level 1': "level_1_count", 
                                'Pct Level 1': "level_1_percentage",
                                'Num Level 2':'level_2_count',
                                'Pct Level 2': 'level_2_percentage',
                                'Num Level 3':"level_3_count",
                                'Pct Level 3': 'level_3_percentage',
                                'Num Level 4':'level_4_count',
                                'Pct Level 4': 'level_4_percentage',
                                'Num Level 3 and 4': "level_3_4_count",
                                'Pct Level 3 and 4': 'level_3_4_percentage'},axis = 'columns')
    return clean_df

In [2]:
import pandas as pd
import numpy as np

In [3]:
da = pd.read_csv('ELA_data_2013_2023.csv')

In [4]:
da2 = da.copy()
cleaned_da = cleaning_data(da2)

In [5]:
cleaned_da

,Report Category,Geographic Subdivision,school_name,Grade,Year,Student Category,number_tested,mean_scale_score,level_1_count,level_1_percentage,level_2_count,level_2_percentage,level_3_count,level_3_percentage,level_4_count,level_4_percentage,level_3_4_count,level_3_4_percentage
0,Citywide,Citywide,NaN,3,2023,All Students,49453,447,14225,28.8,11486,23.2,14154,28.6,9588,19.4,23742,48.0
1,Citywide,Citywide,NaN,4,2023,All Students,51008,450,10679,20.9,13530,26.5,14788,29.0,12011,23.5,26799,52.5
2,Citywide,Citywide,NaN,5,2023,All Students,53235,449,12486,23.5,14190,26.7,16717,31.4,9842,18.5,26559,49.9
3,Citywide,Citywide,NaN,6,2023,All Students,51996,447,13237,25.5,13882,26.7,13709,26.4,11168,21.5,24877,47.8
4,Citywide,Citywide,NaN,7,2023,All Students,53472,450,12976,24.3,12860,24.0,15838,29.6,11798,22.1,27636,51.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626423,School,32K562,EVERGREEN MIDDLE SCHOOL FOR URBAN EXPLORATION,7,2018,SWD,27,587,18,66.7,7,25.9,2,7.4,0,0.0,2,7.4
626424,School,32K562,EVERGREEN MIDDLE SCHOOL FOR URBAN EXPLORATION,8,2018,Not SWD,67,593,12,17.9,41,61.2,12,17.9,2,3.0,14,20.9
626425,School,32K562,EVERGREEN MIDDLE SCHOOL FOR URBAN EXPLORATION,8,2018,SWD,23,586,12,52.2,7,30.4,4,17.4,0,0.0,4,17.4
626426,School,32K562,EVERGREEN MIDDLE SCHOOL FOR URBAN EXPLORATION,All Grades,2018,Not SWD,253,595,68,26.9,119,47.0,54,21.3,12,4.7,66,26.1
626427,School,32K562,EVERGREEN MIDDLE SCHOOL FOR URBAN EXPLORATION,All Grades,2018,SWD,64,585,43,67.2,14,21.9,6,9.4,1,1.6,7,10.9

In [6]:
def create_school_level_data(df):
    ''' Filters data for school level information for all grades and all students. Returns new dataframe'''

    # filtering for school level data, all grades, all students
    df = df[
        (df['Report Category'].isin(['School'])) &
        # (df['Grade'] == 'All Grades') 
        (df['Student Category'] == 'All Students')
    ]
    return df

In [7]:
school_da = create_school_level_data(cleaned_da)

In [8]:
school_da

,Report Category,Geographic Subdivision,school_name,Grade,Year,Student Category,number_tested,mean_scale_score,level_1_count,level_1_percentage,level_2_count,level_2_percentage,level_3_count,level_3_percentage,level_4_count,level_4_percentage,level_3_4_count,level_3_4_percentage
38243,School,01M015,P.S. 015 ROBERTO CLEMENTE,3,2023,All Students,24,455,4,16.7,5,20.8,11,45.8,4,16.7,15,62.5
38244,School,01M015,P.S. 015 ROBERTO CLEMENTE,4,2023,All Students,17,454,1,5.9,6,35.3,8,47.1,2,11.8,10,58.8
38245,School,01M015,P.S. 015 ROBERTO CLEMENTE,5,2023,All Students,30,441,10,33.3,11,36.7,7,23.3,2,6.7,9,30.0
38246,School,01M015,P.S. 015 ROBERTO CLEMENTE,6,2023,All Students,1,s,s,s,s,s,s,s,s,s,s,s
38247,School,01M015,P.S. 015 ROBERTO CLEMENTE,All Grades,2023,All Students,72,s,s,s,s,s,s,s,s,s,s,s
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80565,School,32K562,EVERGREEN MIDDLE SCHOOL FOR URBAN EXPLORATION,All Grades,2019,All Students,323,593,113,35.0,114,35.3,73,22.6,23,7.1,96,29.7
80566,School,32K562,EVERGREEN MIDDLE SCHOOL FOR URBAN EXPLORATION,6,2018,All Students,111,595,37,33.3,37,33.3,26,23.4,11,9.9,37,33.3
80567,School,32K562,EVERGREEN MIDDLE SCHOOL FOR URBAN EXPLORATION,7,2018,All Students,116,592,50,43.1,48,41.4,18,15.5,0,0.0,18,15.5
80568,School,32K562,EVERGREEN MIDDLE SCHOOL FOR URBAN EXPLORATION,8,2018,All Students,90,591,24,26.7,48,53.3,16,17.8,2,2.2,18,20.0
80569,School,32K562,EVERGREEN MIDDLE SCHOOL FOR URBAN EXPLORATION,All Grades,2018,All Students,317,593,111,35.0,133,42.0,60,18.9,13,4.1,73,23.0

In [12]:
school_da['mean_scale_score'] = pd.to_numeric(school_da['mean_scale_score'], errors='coerce')

C:\Users\madis\AppData\Local\Temp\ipykernel_31588\92368430.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  school_da['mean_scale_score'] = pd.to_numeric(school_da['mean_scale_score'], errors='coerce')

In [13]:
print(school_da.groupby("Year")["mean_scale_score"].agg(["mean", "std", "min", "max"]).round(3))

         mean     std    min    max
Year
2018  600.537   9.853  558.0  639.0
2019  599.692  10.013  559.0  644.0
2022  600.037  10.380  567.0  635.0
2023  448.425  11.408  405.0  491.0